name: Build CaeruleumCore

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: "github.actor != 'dependabot[bot]'"
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          java-version: 21
          distribution: zulu

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew clean build

      - name: Release CaeruleumCore
        uses: marvinpinto/action-automatic-releases@master
        with:
          title: "CaeruleumCore v1"
          automatic_release_tag: "dev-build"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: "build/libs/*.jar"
          prerelease: false
